# ============================================================================
# 13. 配置文件 config.yaml
# ============================================================================



detection: 
  model_type: vit_b              # SAM模型类型: vit_b, vit_l, vit_h
  mode: auto                     # 检测模式: auto, grid, hybrid
  min_colony_area: 5000          # 最小菌落面积
  expand_pixels: 8               # 掩码扩展像素数
  merge_overlapping: true        # 是否合并重叠菌落
  use_preprocessing: true        # 是否使用图像预处理
  overlap_threshold: 0.3         # 重叠阈值

sam: 
  points_per_side: 64            # 每边采样点数
  pred_iou_thresh: 0.85          # IoU阈值
  stability_score_thresh: 0.8    # 稳定性分数阈值
  min_mask_region_area: 1500     # 最小掩码区域面积
  crop_n_layers: 1               # 裁剪层数
  crop_n_points_downscale_factor: 1  # 下采样因子

analysis: 
  advanced: false                # 是否启用高级分析
  learning_enabled: false        # 是否启用学习系统
  aerial_threshold: 0.6          # 气生菌丝阈值
  metabolite_threshold: 0.5      # 代谢产物阈值
  enable_parallel: false         # 是否启用并行处理
  max_workers: 4                 # 最大工作线程数

output: 
  debug: false                   # 是否生成调试输出
  well_plate: false              # 是否使用孔板编号
  rows: 8                        # 孔板行数
  cols: 12                       # 孔板列数
  save_masks: true               # 是否保存掩码
  save_visualizations: true      # 是否保存可视化
  image_format: jpg              # 图像输出格式

logging: 
  level: INFO                    # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_to_file: true              # 是否记录到文件
  log_dir: null                  # 日志目录 (null = 自动)
  max_log_files: 10              # 最大日志文件数
