# ============================================================================
# 13. 配置文件 config.yaml
# ============================================================================



detection: 
  model_type: vit_b              # SAM模型类型: vit_b, vit_l, vit_h
  mode: hybird                     # 检测模式: auto, grid, hybrid
  min_colony_area: 500         # 最小菌落面积
  max_colony_area: 50000   # 最大菌落面积
  expand_pixels: 2               # 掩码扩展像素数
  merge_overlapping: true        # 是否合并重叠菌落
  use_preprocessing: true        # 是否使用图像预处理
  overlap_threshold: 0.3         # 重叠阈值
  # 增强功能开关
  enable_adaptive_grid: true      # 启用自适应网格调整
  sort_by_quality: true           # 按质量分数排序结果
  min_quality_score: 0.3          # 最低质量分数阈值
  
  # Hybrid模式参数
  min_colonies_expected: 30       # 预期最少菌落数
  max_mapping_distance: 0.4       # 最大映射距离（相对于孔位大小）
  supplement_score_threshold: 0.5 # 补充检测的分数阈值
  edge_margin_ratio: 0.08         # 边缘边距比例
  
  # 跨界处理参数
  cross_boundary_overlap_threshold: 0.1  # 跨界判定的重叠阈值
  mark_cross_boundary: true              # 是否标记跨界菌落

sam: 
  points_per_side: 64            # 每边采样点数
  pred_iou_thresh: 0.75          # IoU阈值
  stability_score_thresh: 0.65    # 稳定性分数阈值
  min_mask_region_area: 50     # 最小掩码区域面积
  crop_n_layers: 1               # 裁剪层数
  crop_n_points_downscale_factor: 1  # 下采样因子

analysis: 
  advanced: false                # 是否启用高级分析
  learning_enabled: false        # 是否启用学习系统
  aerial_threshold: 0.6          # 气生菌丝阈值
  metabolite_threshold: 0.5      # 代谢产物阈值
  enable_parallel: false         # 是否启用并行处理
  max_workers: 4                 # 最大工作线程数

output: 
  debug: true                   # 是否生成调试输出
  well_plate: false              # 是否使用孔板编号
  rows: 8                        # 孔板行数
  cols: 12                       # 孔板列数
  save_masks: true               # 是否保存掩码
  save_visualizations: true      # 是否保存可视化
  image_format: jpg              # 图像输出格式

logging: 
  level: DEBUG                    # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_to_file: true              # 是否记录到文件
  log_dir: null                  # 日志目录 (null = 自动)
  max_log_files: 10              # 最大日志文件数
